#!/usr/bin/python

import sys
import subprocess
import os

def rawReport(TOOL, PATH, CMD):
    FILE = PATH + TOOL + "RawReport"
    CMD = CMD + " 2> " + FILE
    status = os.system(CMD)
    return status

def main() :
    TOOL = sys.argv[1]
    PATH = sys.argv[2]
    CMD = raw_input("Enter the command for tool " + TOOL + ": ")
    print("[PROCESS] Generating raw report...")
    if rawReport(TOOL, PATH, CMD) != 0:
        print("[ERROR] Not a valid command!\nExit with status code 1")
        exit(1)
    print("[COMPLETE] Raw report generated")
    print("[PROCESS] Processing report..")

if __name__ == "__main__" :
	main()
