#!/usr/bin/python3

import sys
import os
import re

def rawReport(FILE, CMD):
    status = os.system(CMD + " 2> " + FILE)
    return status

def processReport(raw_file, track_file):
    prev_rc_pair = -1
    finding = ""
    regex = re.compile(r'\d+.\d+')
    with open(raw_file) as raw_fh:
        for line in raw_fh:
            obj = regex.search(line)
            if obj != None and obj.group() != prev_rc_pair:
                if len(finding) > 0:
                    print(finding+"\n\n")
                prev_rc_pair = obj.group()
                finding = line
            elif len(finding) > 0:
                finding += line

def main():
    TOOL = sys.argv[1]
    PATH = sys.argv[2]
    RAW_FILE = PATH + TOOL + "RawReport"
    TRACK_FILE = PATH + TOOL + "TrackFindings"
    CMD = input("Enter the command for tool " + TOOL + ": ")
    print("[PROCESS] Generating raw report...")
    if rawReport(RAW_FILE, CMD) != 0:
        print("[ERROR] Not a valid command!\n Exit with status code 1")
        exit(1)
    print("[COMPLETE] Raw report generated")
    print("[PROCESS] Processing report..")
    processReport(RAW_FILE, TRACK_FILE)

if __name__ == "__main__" :
	main()
