#!/bin/bash
#
#Copyright (c) 2020 Priti Chattopadhyay

if [ -d "$PWD/.prit" ]; then
	echo 'Already a Prit Project!'
	exit 1
fi
`mkdir $PWD/.prit`
echo "Initialized an empty Prit Project in $PWD/.prit/"
