#!/bin/bash
#
#Copyright (c) 2020 Priti Chattopadhyay

die () {
	echo "$@" >&2
	exit 1
}

check_dir () {
	if [ -d $1 ]; then
		true
	elif [ "$PWD" = / ]; then
		false
	else
		(cd .. && check_dir $1)
	fi
}

path () {
	if [ -d $1 ]; then
		echo "${PWD%/}/$1"
	elif [ "$PWD" = / ]; then
		false
	else
		(cd .. && path $1)
	fi
}
