#!/bin/sh
#
#Copyright (c) 2020 Priti Chattopadhyay

PRIT_DIR=.prit
. prit-common 

usage () {
	die 'prit analyze [-n] <tool-name>'
}

check_dir "$PRIT_DIR" || die 'Not a Prit Project! Run: prit init'

while case "$#" in 0) usage ;; esac
do
	case "$1" in
    	-n) shift
        	case "$#" in
        	0) usage ;;
        	*) for arg in "$@"
		   do
			prit-setup-tool $arg || die ''
			prit-analysis $arg
		   done
           	exit ;;
        	esac
        	;;
	-*)  die 'Option' $1 'is not supported';;

    	*) for arg in "$@"
	   do	
		check_dir "$PRIT_DIR/.prit-$arg" || 
			die "$arg is not setup. Use -n for new tool" 
		prit-analysis $arg
	   done
	break
        ;;
    	esac
    	shift
done

